In [211]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib as plt

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/pre-cog/judges_clean/judges_clean.csv
/kaggle/input/pre-cog/acts_sections/acts_sections.csv
/kaggle/input/pre-cog/cases/cases_2015.csv
/kaggle/input/pre-cog/cases/cases_2012.csv
/kaggle/input/pre-cog/cases/cases_2018.csv
/kaggle/input/pre-cog/cases/cases_2013.csv
/kaggle/input/pre-cog/cases/cases_2017.csv
/kaggle/input/pre-cog/cases/cases_2010.csv
/kaggle/input/pre-cog/cases/cases_2014.csv
/kaggle/input/pre-cog/cases/cases_2016.csv
/kaggle/input/pre-cog/cases/cases_2011.csv
/kaggle/input/pre-cog/keys/type_name_key.csv
/kaggle/input/pre-cog/keys/cases_district_key.csv
/kaggle/input/pre-cog/keys/act_key.csv
/kaggle/input/pre-cog/keys/disp_name_key.csv
/kaggle/input/pre-cog/keys/purpose_name_key.csv
/kaggle/input/pre-cog/keys/cases_state_key.csv
/kaggle/input/pre-cog/keys/section_key.csv
/kaggle/input/pre-cog/keys/cases_court_key.csv
/kaggle/input/pre-cog/keys/judge_case_merge_key.csv

In [212]:
case_2018 = pd.read_csv('/kaggle/input/pre-cog/cases/cases_2018.csv')
print(case_2018.head())

                ddl_case_id  year  state_code  dist_code  court_no  \
0  01-01-01-201900000012018  2018           1          1         1
1  01-01-01-201900000022018  2018           1          1         1
2  01-01-01-201900000032018  2018           1          1         1
3  01-01-01-201900000042018  2018           1          1         1
4  01-01-01-201900000052018  2018           1          1         1

               cino             judge_position female_defendant  \
0  MHNB030000022018  chief judicial magistrate           0 male
1  MHNB030000032018  chief judicial magistrate           0 male
2  MHNB030000042018  chief judicial magistrate           0 male
3  MHNB030000052018  chief judicial magistrate           0 male
4  MHNB030000062018  chief judicial magistrate    -9998 unclear

  female_petitioner  female_adv_def  female_adv_pet  type_name  purpose_name  \
0            0 male           -9999               0       1943        2975.0
1            0 male           -9999               0       1943        3315.0
2            0 male           -9999               0       1943        5877.0
3            0 male           -9999               0       1943         840.0
4            0 male           -9999               1       1943         840.0

   disp_name date_of_filing date_of_decision date_first_list date_last_list  \
0         33     2018-01-01       2018-02-07      2018-01-01     2018-02-07
1         52     2018-01-01       2018-02-01      2018-01-01     2018-02-01
2         52     2018-01-01       2018-02-01      2018-01-01     2018-02-01
3         52     2018-01-01       2018-02-01      2018-01-01     2018-02-01
4          5     2018-01-01       2018-01-09      2018-01-01     2018-01-09

  date_next_list
0     2018-02-07
1     2018-02-01
2     2018-02-01
3     2018-02-01
4     2018-01-09

In [213]:
case_2018_a = case_2018.drop(case_2018.iloc[:, 3:7],
                       axis = 1)
print(case_2018_a.head())

                ddl_case_id  year  state_code female_defendant  \
0  01-01-01-201900000012018  2018           1           0 male
1  01-01-01-201900000022018  2018           1           0 male
2  01-01-01-201900000032018  2018           1           0 male
3  01-01-01-201900000042018  2018           1           0 male
4  01-01-01-201900000052018  2018           1    -9998 unclear

  female_petitioner  female_adv_def  female_adv_pet  type_name  purpose_name  \
0            0 male           -9999               0       1943        2975.0
1            0 male           -9999               0       1943        3315.0
2            0 male           -9999               0       1943        5877.0
3            0 male           -9999               0       1943         840.0
4            0 male           -9999               1       1943         840.0

   disp_name date_of_filing date_of_decision date_first_list date_last_list  \
0         33     2018-01-01       2018-02-07      2018-01-01     2018-02-07
1         52     2018-01-01       2018-02-01      2018-01-01     2018-02-01
2         52     2018-01-01       2018-02-01      2018-01-01     2018-02-01
3         52     2018-01-01       2018-02-01      2018-01-01     2018-02-01
4          5     2018-01-01       2018-01-09      2018-01-01     2018-01-09

  date_next_list
0     2018-02-07
1     2018-02-01
2     2018-02-01
3     2018-02-01
4     2018-01-09

In [214]:
case_2018_b = case_2018_a.drop(case_2018_a.iloc[:, 10:15],
                       axis = 1)
print(case_2018_b.head())

                ddl_case_id  year  state_code female_defendant  \
0  01-01-01-201900000012018  2018           1           0 male
1  01-01-01-201900000022018  2018           1           0 male
2  01-01-01-201900000032018  2018           1           0 male
3  01-01-01-201900000042018  2018           1           0 male
4  01-01-01-201900000052018  2018           1    -9998 unclear

  female_petitioner  female_adv_def  female_adv_pet  type_name  purpose_name  \
0            0 male           -9999               0       1943        2975.0
1            0 male           -9999               0       1943        3315.0
2            0 male           -9999               0       1943        5877.0
3            0 male           -9999               0       1943         840.0
4            0 male           -9999               1       1943         840.0

   disp_name
0         33
1         52
2         52
3         52
4          5

In [215]:
type_name = pd.read_csv('/kaggle/input/pre-cog/keys/type_name_key.csv')
print(type_name.head())

   year  type_name         type_name_s  count
0  2010        1.0            (m) t.s.     18
1  2010        2.0                (sc)      2
2  2010        3.0          ..mact 166     97
3  2010        4.0  04 complaint cases     19
4  2010        5.0    04 criminal case     21

In [216]:
type_name.drop(type_name[type_name['year'] != 2018].index, inplace = True)

In [217]:
print(type_name.head())

       year  type_name            type_name_s  count
55181  2018        1.0               (m) t.s.    167
55182  2018        2.0  (mac) money execution      5
55183  2018        3.0               0.s.(la)      1
55184  2018        4.0    01 bail_application    355
55185  2018        5.0     01 criminal appeal     14

In [218]:
type_name.reset_index()

      index  year  type_name            type_name_s  count
0     55181  2018        1.0               (m) t.s.    167
1     55182  2018        2.0  (mac) money execution      5
2     55183  2018        3.0               0.s.(la)      1
3     55184  2018        4.0    01 bail_application    355
4     55185  2018        5.0     01 criminal appeal     14
...     ...   ...        ...                    ...    ...
7528  62709  2018     7529.0        xxxxxspl t.ndps      3
7529  62710  2018     7530.0     zila panchayat act    217
7530  62711  2018     7531.0    zilla panchayat act     17
7531  62712  2018     7532.0       zima 457 cr.p.c.      9
7532  62713  2018     7533.0      zimma application     54

[7533 rows x 5 columns]

In [219]:
type_name = type_name[(type_name['type_name_s'] == "divo cases") | (type_name['type_name_s'] == "divorce") | (type_name['type_name_s'] == "divorce case") | (type_name['type_name_s'] == "divorce on mutual consent") | (type_name['type_name_s'] == "divorce suit") | (type_name['type_name_s'] == "dmc") | (type_name['type_name_s'] == "dom viol") | (type_name['type_name_s'] == "domestic violence") | (type_name['type_name_s'] == "domestic violence ac") | (type_name['type_name_s'] == "domestic violence act 2005") | (type_name['type_name_s'] == "domestic violence act.") | (type_name['type_name_s'] == "domestic violence cases") | (type_name['type_name_s'] == "domestic voilenceact") | (type_name['type_name_s'] == "domestice violence act") | (type_name['type_name_s'] == "dop") | (type_name['type_name_s'] == "dowry prohibition act")]

In [220]:
print(type_name)

       year  type_name                 type_name_s  count
57606  2018     2426.0                  divo cases    165
57607  2018     2427.0                     divorce    334
57608  2018     2428.0                divorce case    395
57610  2018     2430.0   divorce on mutual consent   1710
57612  2018     2432.0                divorce suit     24
57614  2018     2434.0                         dmc  13122
57617  2018     2437.0                    dom viol      1
57622  2018     2442.0           domestic violence   1004
57624  2018     2444.0        domestic violence ac    161
57626  2018     2446.0  domestic violence act 2005   1883
57629  2018     2449.0      domestic violence act.   1483
57631  2018     2451.0     domestic violence cases    369
57633  2018     2453.0        domestic voilenceact    334
57634  2018     2454.0      domestice violence act    899
57636  2018     2456.0                         dop    720
57639  2018     2459.0       dowry prohibition act     89

In [221]:
type_name = type_name.drop(['year'], axis=1)

In [222]:
mer_2018 = case_2018_b.merge(type_name, left_on="type_name", right_on="type_name", how="left")
print(mer_2018.head())

                ddl_case_id  year  state_code female_defendant  \
0  01-01-01-201900000012018  2018           1           0 male
1  01-01-01-201900000022018  2018           1           0 male
2  01-01-01-201900000032018  2018           1           0 male
3  01-01-01-201900000042018  2018           1           0 male
4  01-01-01-201900000052018  2018           1    -9998 unclear

  female_petitioner  female_adv_def  female_adv_pet  type_name  purpose_name  \
0            0 male           -9999               0       1943        2975.0
1            0 male           -9999               0       1943        3315.0
2            0 male           -9999               0       1943        5877.0
3            0 male           -9999               0       1943         840.0
4            0 male           -9999               1       1943         840.0

   disp_name type_name_s  count
0         33         NaN    NaN
1         52         NaN    NaN
2         52         NaN    NaN
3         52         NaN    NaN
4          5         NaN    NaN

In [223]:
mer_2018.dropna(subset=['type_name_s'], inplace=True)
print(mer_2018.head())

                     ddl_case_id  year  state_code female_defendant  \
678488  01-23-02-201300000012018  2018           1           0 male
678489  01-23-02-201300000022018  2018           1           0 male
678490  01-23-02-201300000032018  2018           1           0 male
678491  01-23-02-201300000042018  2018           1           0 male
678492  01-23-02-201300000052018  2018           1           0 male

       female_petitioner  female_adv_def  female_adv_pet  type_name  \
678488          1 female           -9999           -9999       2451
678489     -9998 unclear           -9999           -9999       2451
678490          1 female           -9999           -9999       2451
678491            0 male           -9999           -9999       2451
678492     -9998 unclear           -9999           -9999       2451

        purpose_name  disp_name              type_name_s  count
678488        3799.0         23  domestic violence cases  369.0
678489        1898.0         52  domestic violence cases  369.0
678490        2811.0         27  domestic violence cases  369.0
678491        2811.0         27  domestic violence cases  369.0
678492        2811.0         27  domestic violence cases  369.0

In [224]:
mer_2018_def = mer_2018

In [225]:
mer_2018.dropna(subset=['female_petitioner'], inplace=True)

In [226]:
mer_2018_final = mer_2018[(mer_2018['female_petitioner'] == "0 male") | (mer_2018['female_petitioner'] == "1 female")]
print(mer_2018_final.head())

                     ddl_case_id  year  state_code female_defendant  \
678488  01-23-02-201300000012018  2018           1           0 male
678490  01-23-02-201300000032018  2018           1           0 male
678491  01-23-02-201300000042018  2018           1           0 male
678493  01-23-02-201300000062018  2018           1           0 male
678494  01-23-02-201300000072018  2018           1    -9998 unclear

       female_petitioner  female_adv_def  female_adv_pet  type_name  \
678488          1 female           -9999           -9999       2451
678490          1 female           -9999           -9999       2451
678491            0 male           -9999           -9999       2451
678493          1 female           -9999           -9999       2451
678494          1 female           -9999           -9999       2451

        purpose_name  disp_name              type_name_s  count
678488        3799.0         23  domestic violence cases  369.0
678490        2811.0         27  domestic violence cases  369.0
678491        2811.0         27  domestic violence cases  369.0
678493        2811.0         27  domestic violence cases  369.0
678494        2811.0         27  domestic violence cases  369.0

In [227]:
fpet = mer_2018_final.groupby(['female_petitioner'])['ddl_case_id'].count().reset_index()
print(fpet)

  female_petitioner  ddl_case_id
0            0 male         9679
1          1 female        11965

In [228]:
fpet.rename(columns={fpet.columns[1]: '2018'},inplace=True)
print(fpet)

  female_petitioner   2018
0            0 male   9679
1          1 female  11965

In [233]:
fpet.to_csv('fpet_2018.csv')

In [229]:
mer_2018_def.dropna(subset=['female_defendant'], inplace=True)

In [230]:
mer_2018_def_final = mer_2018_def[(mer_2018_def['female_defendant'] == "0 male") | (mer_2018['female_defendant'] == "1 female")]
print(mer_2018_def_final.head())

                     ddl_case_id  year  state_code female_defendant  \
678488  01-23-02-201300000012018  2018           1           0 male
678489  01-23-02-201300000022018  2018           1           0 male
678490  01-23-02-201300000032018  2018           1           0 male
678491  01-23-02-201300000042018  2018           1           0 male
678492  01-23-02-201300000052018  2018           1           0 male

       female_petitioner  female_adv_def  female_adv_pet  type_name  \
678488          1 female           -9999           -9999       2451
678489     -9998 unclear           -9999           -9999       2451
678490          1 female           -9999           -9999       2451
678491            0 male           -9999           -9999       2451
678492     -9998 unclear           -9999           -9999       2451

        purpose_name  disp_name              type_name_s  count
678488        3799.0         23  domestic violence cases  369.0
678489        1898.0         52  domestic violence cases  369.0
678490        2811.0         27  domestic violence cases  369.0
678491        2811.0         27  domestic violence cases  369.0
678492        2811.0         27  domestic violence cases  369.0

In [231]:
fdef = mer_2018_def_final.groupby(['female_defendant'])['ddl_case_id'].count().reset_index()
print(fdef)

  female_defendant  ddl_case_id
0           0 male        13632
1         1 female         7887

In [232]:
fdef.rename(columns={fdef.columns[1]: '2018'},inplace=True)
print(fdef)

  female_defendant   2018
0           0 male  13632
1         1 female   7887

In [234]:
fdef.to_csv('fdef_2018.csv')