In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib as plt

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/pre-cog/judges_clean/judges_clean.csv
/kaggle/input/pre-cog/acts_sections/acts_sections.csv
/kaggle/input/pre-cog/cases/cases_2015.csv
/kaggle/input/pre-cog/cases/cases_2012.csv
/kaggle/input/pre-cog/cases/cases_2018.csv
/kaggle/input/pre-cog/cases/cases_2013.csv
/kaggle/input/pre-cog/cases/cases_2017.csv
/kaggle/input/pre-cog/cases/cases_2010.csv
/kaggle/input/pre-cog/cases/cases_2014.csv
/kaggle/input/pre-cog/cases/cases_2016.csv
/kaggle/input/pre-cog/cases/cases_2011.csv
/kaggle/input/pre-cog/keys/type_name_key.csv
/kaggle/input/pre-cog/keys/cases_district_key.csv
/kaggle/input/pre-cog/keys/act_key.csv
/kaggle/input/pre-cog/keys/disp_name_key.csv
/kaggle/input/pre-cog/keys/purpose_name_key.csv
/kaggle/input/pre-cog/keys/cases_state_key.csv
/kaggle/input/pre-cog/keys/section_key.csv
/kaggle/input/pre-cog/keys/cases_court_key.csv
/kaggle/input/pre-cog/keys/judge_case_merge_key.csv

In [2]:
case_2018 = pd.read_csv('/kaggle/input/pre-cog/cases/cases_2014.csv')
print(case_2018.head())

                ddl_case_id  year  state_code  dist_code  court_no  \
0  01-01-01-201908000022014  2014           1          1         1
1  01-01-01-201908000032014  2014           1          1         1
2  01-01-01-201908000052014  2014           1          1         1
3  01-01-01-201908000062014  2014           1          1         1
4  01-01-01-201908000072014  2014           1          1         1

               cino             judge_position female_defendant  \
0  MHNB030000982014  chief judicial magistrate    -9998 unclear
1  MHNB030001052014  chief judicial magistrate           0 male
2  MHNB030001302014  chief judicial magistrate           0 male
3  MHNB030000512014  chief judicial magistrate           0 male
4  MHNB030000522014  chief judicial magistrate           0 male

  female_petitioner  female_adv_def  female_adv_pet  type_name  purpose_name  \
0            0 male           -9999           -9998     1907.0        5487.0
1          1 female           -9999               1     1907.0        6304.0
2          1 female           -9999               0     1907.0        4366.0
3          1 female           -9998               0     1907.0        4823.0
4            0 male           -9999               0     1907.0        5487.0

   disp_name date_of_filing date_of_decision date_first_list date_last_list  \
0         25     2014-01-03       2014-10-28      2014-01-16     2014-09-30
1         25     2014-01-01       2015-08-10      2014-02-11     2015-08-03
2         25     2014-01-02       2014-06-10      2014-02-12     2014-05-29
3         22     2014-01-04       2016-11-14      2014-01-04     2016-11-14
4         25     2014-01-04       2014-01-04      2014-01-04     2014-01-04

  date_next_list
0     2014-10-28
1     2015-08-10
2     2014-06-10
3     2016-11-14
4     2014-01-04

In [3]:
case_2018_a = case_2018.drop(case_2018.iloc[:, 3:7],
                       axis = 1)
print(case_2018_a.head())

                ddl_case_id  year  state_code female_defendant  \
0  01-01-01-201908000022014  2014           1    -9998 unclear
1  01-01-01-201908000032014  2014           1           0 male
2  01-01-01-201908000052014  2014           1           0 male
3  01-01-01-201908000062014  2014           1           0 male
4  01-01-01-201908000072014  2014           1           0 male

  female_petitioner  female_adv_def  female_adv_pet  type_name  purpose_name  \
0            0 male           -9999           -9998     1907.0        5487.0
1          1 female           -9999               1     1907.0        6304.0
2          1 female           -9999               0     1907.0        4366.0
3          1 female           -9998               0     1907.0        4823.0
4            0 male           -9999               0     1907.0        5487.0

   disp_name date_of_filing date_of_decision date_first_list date_last_list  \
0         25     2014-01-03       2014-10-28      2014-01-16     2014-09-30
1         25     2014-01-01       2015-08-10      2014-02-11     2015-08-03
2         25     2014-01-02       2014-06-10      2014-02-12     2014-05-29
3         22     2014-01-04       2016-11-14      2014-01-04     2016-11-14
4         25     2014-01-04       2014-01-04      2014-01-04     2014-01-04

  date_next_list
0     2014-10-28
1     2015-08-10
2     2014-06-10
3     2016-11-14
4     2014-01-04

In [4]:
case_2018_b = case_2018_a.drop(case_2018_a.iloc[:, 10:15],
                       axis = 1)
print(case_2018_b.head())

                ddl_case_id  year  state_code female_defendant  \
0  01-01-01-201908000022014  2014           1    -9998 unclear
1  01-01-01-201908000032014  2014           1           0 male
2  01-01-01-201908000052014  2014           1           0 male
3  01-01-01-201908000062014  2014           1           0 male
4  01-01-01-201908000072014  2014           1           0 male

  female_petitioner  female_adv_def  female_adv_pet  type_name  purpose_name  \
0            0 male           -9999           -9998     1907.0        5487.0
1          1 female           -9999               1     1907.0        6304.0
2          1 female           -9999               0     1907.0        4366.0
3          1 female           -9998               0     1907.0        4823.0
4            0 male           -9999               0     1907.0        5487.0

   disp_name
0         25
1         25
2         25
3         22
4         25

In [5]:
type_name = pd.read_csv('/kaggle/input/pre-cog/keys/type_name_key.csv')
print(type_name.head())

   year  type_name         type_name_s  count
0  2010        1.0            (m) t.s.     18
1  2010        2.0                (sc)      2
2  2010        3.0          ..mact 166     97
3  2010        4.0  04 complaint cases     19
4  2010        5.0    04 criminal case     21

In [6]:
type_name.drop(type_name[type_name['year'] != 2014].index, inplace = True)

In [7]:
print(type_name.head())

       year  type_name           type_name_s  count
25588  2014        NaN                   NaN      6
25589  2014        1.0                (d.v.)      1
25590  2014        2.0              (m) t.s.    121
25591  2014        3.0            ..mact 166     16
25592  2014        4.0  01 criminal_revision      1

In [8]:
type_name.reset_index()

      index  year  type_name           type_name_s  count
0     25588  2014        NaN                   NaN      6
1     25589  2014        1.0                (d.v.)      1
2     25590  2014        2.0              (m) t.s.    121
3     25591  2014        3.0            ..mact 166     16
4     25592  2014        4.0  01 criminal_revision      1
...     ...   ...        ...                   ...    ...
7170  32758  2014     7170.0       xxxxxspl t.ndps      1
7171  32759  2014     7171.0              yaddasta      1
7172  32760  2014     7172.0     zcivil misc. case      1
7173  32761  2014     7173.0   zilla panchayat act     17
7174  32762  2014     7174.0     zimma application      5

[7175 rows x 5 columns]

In [9]:
type_name = type_name[(type_name['type_name_s'] == "divo cases") | (type_name['type_name_s'] == "divorce") | (type_name['type_name_s'] == "divorce case") | (type_name['type_name_s'] == "divorce on mutual consent") | (type_name['type_name_s'] == "divorce suit") | (type_name['type_name_s'] == "dmc") | (type_name['type_name_s'] == "dom viol") | (type_name['type_name_s'] == "domestic violence") | (type_name['type_name_s'] == "domestic violence ac") | (type_name['type_name_s'] == "domestic violence act 2005") | (type_name['type_name_s'] == "domestic violence act.") | (type_name['type_name_s'] == "domestic violence cases") | (type_name['type_name_s'] == "domestic voilenceact") | (type_name['type_name_s'] == "domestice violence act") | (type_name['type_name_s'] == "dop") | (type_name['type_name_s'] == "dowry prohibition act")]

In [10]:
print(type_name)

       year  type_name                 type_name_s  count
27963  2014     2375.0                  divo cases    148
27964  2014     2376.0                     divorce    291
27965  2014     2377.0                divorce case    244
27968  2014     2380.0   divorce on mutual consent   2238
27969  2014     2381.0                divorce suit      1
27971  2014     2383.0                         dmc   9857
27974  2014     2386.0                    dom viol     65
27980  2014     2392.0           domestic violence    575
27982  2014     2394.0        domestic violence ac     82
27984  2014     2396.0  domestic violence act 2005   2490
27986  2014     2398.0      domestic violence act.   1293
27988  2014     2400.0     domestic violence cases    253
27991  2014     2403.0        domestic voilenceact     79
27992  2014     2404.0      domestice violence act    267
27994  2014     2406.0                         dop    319
27995  2014     2407.0       dowry prohibition act     32

In [11]:
type_name = type_name.drop(['year'], axis=1)

In [12]:
mer_2018 = case_2018_b.merge(type_name, left_on="type_name", right_on="type_name", how="left")
print(mer_2018.head())

                ddl_case_id  year  state_code female_defendant  \
0  01-01-01-201908000022014  2014           1    -9998 unclear
1  01-01-01-201908000032014  2014           1           0 male
2  01-01-01-201908000052014  2014           1           0 male
3  01-01-01-201908000062014  2014           1           0 male
4  01-01-01-201908000072014  2014           1           0 male

  female_petitioner  female_adv_def  female_adv_pet  type_name  purpose_name  \
0            0 male           -9999           -9998     1907.0        5487.0
1          1 female           -9999               1     1907.0        6304.0
2          1 female           -9999               0     1907.0        4366.0
3          1 female           -9998               0     1907.0        4823.0
4            0 male           -9999               0     1907.0        5487.0

   disp_name type_name_s  count
0         25         NaN    NaN
1         25         NaN    NaN
2         25         NaN    NaN
3         22         NaN    NaN
4         25         NaN    NaN

In [13]:
mer_2018.dropna(subset=['type_name_s'], inplace=True)
print(mer_2018.head())

                     ddl_case_id  year  state_code female_defendant  \
547794  01-23-02-201300000012014  2014           1           0 male
547795  01-23-02-201300000022014  2014           1           0 male
547796  01-23-02-201300000052014  2014           1           0 male
547797  01-23-02-201300000062014  2014           1           0 male
547798  01-23-02-201300000072014  2014           1           0 male

       female_petitioner  female_adv_def  female_adv_pet  type_name  \
547794          1 female           -9999           -9999     2400.0
547795          1 female           -9999           -9999     2400.0
547796          1 female           -9999           -9999     2400.0
547797            0 male           -9999           -9999     2400.0
547798          1 female           -9999           -9999     2400.0

        purpose_name  disp_name              type_name_s  count
547794        2642.0         33  domestic violence cases  253.0
547795        2642.0         26  domestic violence cases  253.0
547796        4823.0         30  domestic violence cases  253.0
547797        2642.0         22  domestic violence cases  253.0
547798        2642.0         22  domestic violence cases  253.0

In [14]:
mer_2018_def = mer_2018

In [15]:
mer_2018.dropna(subset=['female_petitioner'], inplace=True)

In [16]:
mer_2018_final = mer_2018[(mer_2018['female_petitioner'] == "0 male") | (mer_2018['female_petitioner'] == "1 female")]
print(mer_2018_final.head())

                     ddl_case_id  year  state_code female_defendant  \
547794  01-23-02-201300000012014  2014           1           0 male
547795  01-23-02-201300000022014  2014           1           0 male
547796  01-23-02-201300000052014  2014           1           0 male
547797  01-23-02-201300000062014  2014           1           0 male
547798  01-23-02-201300000072014  2014           1           0 male

       female_petitioner  female_adv_def  female_adv_pet  type_name  \
547794          1 female           -9999           -9999     2400.0
547795          1 female           -9999           -9999     2400.0
547796          1 female           -9999           -9999     2400.0
547797            0 male           -9999           -9999     2400.0
547798          1 female           -9999           -9999     2400.0

        purpose_name  disp_name              type_name_s  count
547794        2642.0         33  domestic violence cases  253.0
547795        2642.0         26  domestic violence cases  253.0
547796        4823.0         30  domestic violence cases  253.0
547797        2642.0         22  domestic violence cases  253.0
547798        2642.0         22  domestic violence cases  253.0

In [17]:
fpet = mer_2018_final.groupby(['female_petitioner'])['ddl_case_id'].count().reset_index()
print(fpet)

  female_petitioner  ddl_case_id
0            0 male         7264
1          1 female        10074

In [18]:
fpet.rename(columns={fpet.columns[1]: '2014'},inplace=True)
print(fpet)

  female_petitioner   2014
0            0 male   7264
1          1 female  10074

In [19]:
fpet.to_csv('fpet_2014.csv')

In [20]:
mer_2018_def.dropna(subset=['female_defendant'], inplace=True)

In [21]:
mer_2018_def_final = mer_2018_def[(mer_2018_def['female_defendant'] == "0 male") | (mer_2018['female_defendant'] == "1 female")]
print(mer_2018_def_final.head())

                     ddl_case_id  year  state_code female_defendant  \
547794  01-23-02-201300000012014  2014           1           0 male
547795  01-23-02-201300000022014  2014           1           0 male
547796  01-23-02-201300000052014  2014           1           0 male
547797  01-23-02-201300000062014  2014           1           0 male
547798  01-23-02-201300000072014  2014           1           0 male

       female_petitioner  female_adv_def  female_adv_pet  type_name  \
547794          1 female           -9999           -9999     2400.0
547795          1 female           -9999           -9999     2400.0
547796          1 female           -9999           -9999     2400.0
547797            0 male           -9999           -9999     2400.0
547798          1 female           -9999           -9999     2400.0

        purpose_name  disp_name              type_name_s  count
547794        2642.0         33  domestic violence cases  253.0
547795        2642.0         26  domestic violence cases  253.0
547796        4823.0         30  domestic violence cases  253.0
547797        2642.0         22  domestic violence cases  253.0
547798        2642.0         22  domestic violence cases  253.0

In [22]:
fdef = mer_2018_def_final.groupby(['female_defendant'])['ddl_case_id'].count().reset_index()
print(fdef)

  female_defendant  ddl_case_id
0           0 male         9830
1         1 female         6556

In [23]:
fdef.rename(columns={fdef.columns[1]: '2014'},inplace=True)
print(fdef)

  female_defendant  2014
0           0 male  9830
1         1 female  6556

In [24]:
fdef.to_csv('fdef_2014.csv')