In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib as plt

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/pre-cog/judges_clean/judges_clean.csv
/kaggle/input/pre-cog/acts_sections/acts_sections.csv
/kaggle/input/pre-cog/cases/cases_2015.csv
/kaggle/input/pre-cog/cases/cases_2012.csv
/kaggle/input/pre-cog/cases/cases_2018.csv
/kaggle/input/pre-cog/cases/cases_2013.csv
/kaggle/input/pre-cog/cases/cases_2017.csv
/kaggle/input/pre-cog/cases/cases_2010.csv
/kaggle/input/pre-cog/cases/cases_2014.csv
/kaggle/input/pre-cog/cases/cases_2016.csv
/kaggle/input/pre-cog/cases/cases_2011.csv
/kaggle/input/pre-cog/keys/type_name_key.csv
/kaggle/input/pre-cog/keys/cases_district_key.csv
/kaggle/input/pre-cog/keys/act_key.csv
/kaggle/input/pre-cog/keys/disp_name_key.csv
/kaggle/input/pre-cog/keys/purpose_name_key.csv
/kaggle/input/pre-cog/keys/cases_state_key.csv
/kaggle/input/pre-cog/keys/section_key.csv
/kaggle/input/pre-cog/keys/cases_court_key.csv
/kaggle/input/pre-cog/keys/judge_case_merge_key.csv

In [2]:
case_2018 = pd.read_csv('/kaggle/input/pre-cog/cases/cases_2017.csv')
print(case_2018.head())

                ddl_case_id  year  state_code  dist_code  court_no  \
0  01-01-01-201900000012017  2017           1          1         1
1  01-01-01-201900000022017  2017           1          1         1
2  01-01-01-201900000032017  2017           1          1         1
3  01-01-01-201900000042017  2017           1          1         1
4  01-01-01-201900000052017  2017           1          1         1

               cino             judge_position female_defendant  \
0  MHNB030000102017  chief judicial magistrate           0 male
1  MHNB030000282017  chief judicial magistrate           0 male
2  MHNB030000292017  chief judicial magistrate    -9998 unclear
3  MHNB030000302017  chief judicial magistrate           0 male
4  MHNB030000312017  chief judicial magistrate    -9998 unclear

  female_petitioner  female_adv_def  female_adv_pet  type_name  purpose_name  \
0            0 male           -9999               0     1943.0        3206.0
1            0 male           -9999               1     1943.0        6212.0
2            0 male           -9999               0     1943.0        6004.0
3            0 male           -9999               1     1943.0        3206.0
4            0 male           -9999               0     1943.0        7122.0

   disp_name date_of_filing date_of_decision date_first_list date_last_list  \
0         26     2017-01-02       2017-03-06      2017-01-02     2017-03-06
1         26     2017-01-04       2017-02-27      2017-01-04     2017-02-27
2         31     2017-01-04       2017-01-21      2017-01-04     2017-01-21
3         31     2017-01-04       2017-02-14      2017-01-04     2017-02-14
4         31     2017-01-04       2017-01-06      2017-01-04     2017-01-06

  date_next_list
0     2017-03-06
1     2017-02-27
2     2017-01-21
3     2017-02-14
4     2017-01-06

In [3]:
case_2018_a = case_2018.drop(case_2018.iloc[:, 3:7],
                       axis = 1)
print(case_2018_a.head())

                ddl_case_id  year  state_code female_defendant  \
0  01-01-01-201900000012017  2017           1           0 male
1  01-01-01-201900000022017  2017           1           0 male
2  01-01-01-201900000032017  2017           1    -9998 unclear
3  01-01-01-201900000042017  2017           1           0 male
4  01-01-01-201900000052017  2017           1    -9998 unclear

  female_petitioner  female_adv_def  female_adv_pet  type_name  purpose_name  \
0            0 male           -9999               0     1943.0        3206.0
1            0 male           -9999               1     1943.0        6212.0
2            0 male           -9999               0     1943.0        6004.0
3            0 male           -9999               1     1943.0        3206.0
4            0 male           -9999               0     1943.0        7122.0

   disp_name date_of_filing date_of_decision date_first_list date_last_list  \
0         26     2017-01-02       2017-03-06      2017-01-02     2017-03-06
1         26     2017-01-04       2017-02-27      2017-01-04     2017-02-27
2         31     2017-01-04       2017-01-21      2017-01-04     2017-01-21
3         31     2017-01-04       2017-02-14      2017-01-04     2017-02-14
4         31     2017-01-04       2017-01-06      2017-01-04     2017-01-06

  date_next_list
0     2017-03-06
1     2017-02-27
2     2017-01-21
3     2017-02-14
4     2017-01-06

In [4]:
case_2018_b = case_2018_a.drop(case_2018_a.iloc[:, 10:15],
                       axis = 1)
print(case_2018_b.head())

                ddl_case_id  year  state_code female_defendant  \
0  01-01-01-201900000012017  2017           1           0 male
1  01-01-01-201900000022017  2017           1           0 male
2  01-01-01-201900000032017  2017           1    -9998 unclear
3  01-01-01-201900000042017  2017           1           0 male
4  01-01-01-201900000052017  2017           1    -9998 unclear

  female_petitioner  female_adv_def  female_adv_pet  type_name  purpose_name  \
0            0 male           -9999               0     1943.0        3206.0
1            0 male           -9999               1     1943.0        6212.0
2            0 male           -9999               0     1943.0        6004.0
3            0 male           -9999               1     1943.0        3206.0
4            0 male           -9999               0     1943.0        7122.0

   disp_name
0         26
1         26
2         31
3         31
4         31

In [5]:
type_name = pd.read_csv('/kaggle/input/pre-cog/keys/type_name_key.csv')
print(type_name.head())

   year  type_name         type_name_s  count
0  2010        1.0            (m) t.s.     18
1  2010        2.0                (sc)      2
2  2010        3.0          ..mact 166     97
3  2010        4.0  04 complaint cases     19
4  2010        5.0    04 criminal case     21

In [6]:
type_name.drop(type_name[type_name['year'] != 2017].index, inplace = True)

In [7]:
print(type_name.head())

       year  type_name            type_name_s  count
47624  2017        NaN                    NaN      1
47625  2017        1.0               (m) t.s.    173
47626  2017        2.0  (mac) money execution      4
47627  2017        3.0               0.s.(la)      1
47628  2017        4.0    01 bail_application    152

In [8]:
type_name.reset_index()

      index  year  type_name            type_name_s  count
0     47624  2017        NaN                    NaN      1
1     47625  2017        1.0               (m) t.s.    173
2     47626  2017        2.0  (mac) money execution      4
3     47627  2017        3.0               0.s.(la)      1
4     47628  2017        4.0    01 bail_application    152
...     ...   ...        ...                    ...    ...
7552  55176  2017     7552.0        xxxxxspl t.ndps      4
7553  55177  2017     7553.0     zila panchayat act    479
7554  55178  2017     7554.0    zilla panchayat act      9
7555  55179  2017     7555.0       zima 457 cr.p.c.      4
7556  55180  2017     7556.0      zimma application     31

[7557 rows x 5 columns]

In [9]:
type_name = type_name[(type_name['type_name_s'] == "divo cases") | (type_name['type_name_s'] == "divorce") | (type_name['type_name_s'] == "divorce case") | (type_name['type_name_s'] == "divorce on mutual consent") | (type_name['type_name_s'] == "divorce suit") | (type_name['type_name_s'] == "dmc") | (type_name['type_name_s'] == "dom viol") | (type_name['type_name_s'] == "domestic violence") | (type_name['type_name_s'] == "domestic violence ac") | (type_name['type_name_s'] == "domestic violence act 2005") | (type_name['type_name_s'] == "domestic violence act.") | (type_name['type_name_s'] == "domestic violence cases") | (type_name['type_name_s'] == "domestic voilenceact") | (type_name['type_name_s'] == "domestice violence act") | (type_name['type_name_s'] == "dop") | (type_name['type_name_s'] == "dowry prohibition act")]

In [10]:
print(type_name)

       year  type_name                 type_name_s  count
50067  2017     2443.0                  divo cases    116
50068  2017     2444.0                     divorce    344
50069  2017     2445.0                divorce case    323
50071  2017     2447.0   divorce on mutual consent   2110
50072  2017     2448.0                divorce suit     28
50074  2017     2450.0                         dmc  11891
50077  2017     2453.0                    dom viol      3
50082  2017     2458.0           domestic violence    855
50084  2017     2460.0        domestic violence ac    105
50086  2017     2462.0  domestic violence act 2005   1683
50089  2017     2465.0      domestic violence act.   1253
50091  2017     2467.0     domestic violence cases    352
50094  2017     2470.0        domestic voilenceact     97
50095  2017     2471.0      domestice violence act    794
50097  2017     2473.0                         dop    512
50099  2017     2475.0       dowry prohibition act     84

In [11]:
type_name = type_name.drop(['year'], axis=1)

In [12]:
mer_2018 = case_2018_b.merge(type_name, left_on="type_name", right_on="type_name", how="left")
print(mer_2018.head())

                ddl_case_id  year  state_code female_defendant  \
0  01-01-01-201900000012017  2017           1           0 male
1  01-01-01-201900000022017  2017           1           0 male
2  01-01-01-201900000032017  2017           1    -9998 unclear
3  01-01-01-201900000042017  2017           1           0 male
4  01-01-01-201900000052017  2017           1    -9998 unclear

  female_petitioner  female_adv_def  female_adv_pet  type_name  purpose_name  \
0            0 male           -9999               0     1943.0        3206.0
1            0 male           -9999               1     1943.0        6212.0
2            0 male           -9999               0     1943.0        6004.0
3            0 male           -9999               1     1943.0        3206.0
4            0 male           -9999               0     1943.0        7122.0

   disp_name type_name_s  count
0         26         NaN    NaN
1         26         NaN    NaN
2         31         NaN    NaN
3         31         NaN    NaN
4         31         NaN    NaN

In [13]:
mer_2018.dropna(subset=['type_name_s'], inplace=True)
print(mer_2018.head())

                     ddl_case_id  year  state_code female_defendant  \
665377  01-23-02-201300000012017  2017           1           0 male
665378  01-23-02-201300000022017  2017           1           0 male
665379  01-23-02-201300000032017  2017           1           0 male
665380  01-23-02-201300000042017  2017           1           0 male
665381  01-23-02-201300000052017  2017           1           0 male

       female_petitioner  female_adv_def  female_adv_pet  type_name  \
665377          1 female           -9999           -9999     2467.0
665378          1 female           -9999           -9999     2467.0
665379          1 female           -9999           -9999     2467.0
665380          1 female           -9999           -9999     2467.0
665381          1 female           -9999           -9998     2467.0

        purpose_name  disp_name              type_name_s  count
665377        3011.0         23  domestic violence cases  352.0
665378        3011.0         27  domestic violence cases  352.0
665379        3011.0         27  domestic violence cases  352.0
665380        4308.0         33  domestic violence cases  352.0
665381        3011.0         27  domestic violence cases  352.0

In [14]:
mer_2018_def = mer_2018

In [15]:
mer_2018.dropna(subset=['female_petitioner'], inplace=True)

In [16]:
mer_2018_final = mer_2018[(mer_2018['female_petitioner'] == "0 male") | (mer_2018['female_petitioner'] == "1 female")]
print(mer_2018_final.head())

                     ddl_case_id  year  state_code female_defendant  \
665377  01-23-02-201300000012017  2017           1           0 male
665378  01-23-02-201300000022017  2017           1           0 male
665379  01-23-02-201300000032017  2017           1           0 male
665380  01-23-02-201300000042017  2017           1           0 male
665381  01-23-02-201300000052017  2017           1           0 male

       female_petitioner  female_adv_def  female_adv_pet  type_name  \
665377          1 female           -9999           -9999     2467.0
665378          1 female           -9999           -9999     2467.0
665379          1 female           -9999           -9999     2467.0
665380          1 female           -9999           -9999     2467.0
665381          1 female           -9999           -9998     2467.0

        purpose_name  disp_name              type_name_s  count
665377        3011.0         23  domestic violence cases  352.0
665378        3011.0         27  domestic violence cases  352.0
665379        3011.0         27  domestic violence cases  352.0
665380        4308.0         33  domestic violence cases  352.0
665381        3011.0         27  domestic violence cases  352.0

In [17]:
fpet = mer_2018_final.groupby(['female_petitioner'])['ddl_case_id'].count().reset_index()
print(fpet)

  female_petitioner  ddl_case_id
0            0 male         8735
1          1 female        10859

In [18]:
fpet.rename(columns={fpet.columns[1]: '2017'},inplace=True)
print(fpet)

  female_petitioner   2017
0            0 male   8735
1          1 female  10859

In [19]:
fpet.to_csv('fpet_2017.csv')

In [20]:
mer_2018_def.dropna(subset=['female_defendant'], inplace=True)

In [21]:
mer_2018_def_final = mer_2018_def[(mer_2018_def['female_defendant'] == "0 male") | (mer_2018['female_defendant'] == "1 female")]
print(mer_2018_def_final.head())

                     ddl_case_id  year  state_code female_defendant  \
665377  01-23-02-201300000012017  2017           1           0 male
665378  01-23-02-201300000022017  2017           1           0 male
665379  01-23-02-201300000032017  2017           1           0 male
665380  01-23-02-201300000042017  2017           1           0 male
665381  01-23-02-201300000052017  2017           1           0 male

       female_petitioner  female_adv_def  female_adv_pet  type_name  \
665377          1 female           -9999           -9999     2467.0
665378          1 female           -9999           -9999     2467.0
665379          1 female           -9999           -9999     2467.0
665380          1 female           -9999           -9999     2467.0
665381          1 female           -9999           -9998     2467.0

        purpose_name  disp_name              type_name_s  count
665377        3011.0         23  domestic violence cases  352.0
665378        3011.0         27  domestic violence cases  352.0
665379        3011.0         27  domestic violence cases  352.0
665380        4308.0         33  domestic violence cases  352.0
665381        3011.0         27  domestic violence cases  352.0

In [22]:
fdef = mer_2018_def_final.groupby(['female_defendant'])['ddl_case_id'].count().reset_index()
print(fdef)

  female_defendant  ddl_case_id
0           0 male        11908
1         1 female         7286

In [23]:
fdef.rename(columns={fdef.columns[1]: '2017'},inplace=True)
print(fdef)

  female_defendant   2017
0           0 male  11908
1         1 female   7286

In [24]:
fdef.to_csv('fdef_2017.csv')