In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib as plt

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/pre-cog/judges_clean/judges_clean.csv
/kaggle/input/pre-cog/acts_sections/acts_sections.csv
/kaggle/input/pre-cog/cases/cases_2015.csv
/kaggle/input/pre-cog/cases/cases_2012.csv
/kaggle/input/pre-cog/cases/cases_2018.csv
/kaggle/input/pre-cog/cases/cases_2013.csv
/kaggle/input/pre-cog/cases/cases_2017.csv
/kaggle/input/pre-cog/cases/cases_2010.csv
/kaggle/input/pre-cog/cases/cases_2014.csv
/kaggle/input/pre-cog/cases/cases_2016.csv
/kaggle/input/pre-cog/cases/cases_2011.csv
/kaggle/input/pre-cog/keys/type_name_key.csv
/kaggle/input/pre-cog/keys/cases_district_key.csv
/kaggle/input/pre-cog/keys/act_key.csv
/kaggle/input/pre-cog/keys/disp_name_key.csv
/kaggle/input/pre-cog/keys/purpose_name_key.csv
/kaggle/input/pre-cog/keys/cases_state_key.csv
/kaggle/input/pre-cog/keys/section_key.csv
/kaggle/input/pre-cog/keys/cases_court_key.csv
/kaggle/input/pre-cog/keys/judge_case_merge_key.csv

In [2]:
case_2018 = pd.read_csv('/kaggle/input/pre-cog/cases/cases_2015.csv')
print(case_2018.head())

                ddl_case_id  year  state_code  dist_code  court_no  \
0  01-01-01-201908000012015  2015           1          1         1
1  01-01-01-201908000022015  2015           1          1         1
2  01-01-01-201908000032015  2015           1          1         1
3  01-01-01-201908000042015  2015           1          1         1
4  01-01-01-201908000052015  2015           1          1         1

               cino             judge_position female_defendant  \
0  MHNB030000242015  chief judicial magistrate    -9998 unclear
1  MHNB030000282015  chief judicial magistrate           0 male
2  MHNB030000272015  chief judicial magistrate           0 male
3  MHNB030000482015  chief judicial magistrate           0 male
4  MHNB030000332015  chief judicial magistrate    -9998 unclear

  female_petitioner  female_adv_def  female_adv_pet  type_name  purpose_name  \
0          1 female           -9999               0     1978.0        6013.0
1          1 female               0               1     1978.0        5446.0
2            0 male           -9999               0     1978.0        6013.0
3            0 male           -9999               0     1978.0        6210.0
4            0 male               0               0     1978.0        6013.0

   disp_name date_of_filing date_of_decision date_first_list date_last_list  \
0         25     2015-01-01       2015-02-25      2015-01-01     2015-02-16
1         30     2015-01-02       2016-12-01      2015-01-02     2016-12-01
2         32     2015-01-02       2015-02-25      2015-01-02     2015-02-16
3         51     2015-01-03       2016-03-21      2015-01-03     2016-03-21
4         25     2015-01-05       2015-01-12      2015-01-05     2015-01-05

  date_next_list
0     2015-02-25
1     2016-12-01
2     2015-02-25
3     2016-03-21
4     2015-01-12

In [3]:
case_2018_a = case_2018.drop(case_2018.iloc[:, 3:7],
                       axis = 1)
print(case_2018_a.head())

                ddl_case_id  year  state_code female_defendant  \
0  01-01-01-201908000012015  2015           1    -9998 unclear
1  01-01-01-201908000022015  2015           1           0 male
2  01-01-01-201908000032015  2015           1           0 male
3  01-01-01-201908000042015  2015           1           0 male
4  01-01-01-201908000052015  2015           1    -9998 unclear

  female_petitioner  female_adv_def  female_adv_pet  type_name  purpose_name  \
0          1 female           -9999               0     1978.0        6013.0
1          1 female               0               1     1978.0        5446.0
2            0 male           -9999               0     1978.0        6013.0
3            0 male           -9999               0     1978.0        6210.0
4            0 male               0               0     1978.0        6013.0

   disp_name date_of_filing date_of_decision date_first_list date_last_list  \
0         25     2015-01-01       2015-02-25      2015-01-01     2015-02-16
1         30     2015-01-02       2016-12-01      2015-01-02     2016-12-01
2         32     2015-01-02       2015-02-25      2015-01-02     2015-02-16
3         51     2015-01-03       2016-03-21      2015-01-03     2016-03-21
4         25     2015-01-05       2015-01-12      2015-01-05     2015-01-05

  date_next_list
0     2015-02-25
1     2016-12-01
2     2015-02-25
3     2016-03-21
4     2015-01-12

In [4]:
case_2018_b = case_2018_a.drop(case_2018_a.iloc[:, 10:15],
                       axis = 1)
print(case_2018_b.head())

                ddl_case_id  year  state_code female_defendant  \
0  01-01-01-201908000012015  2015           1    -9998 unclear
1  01-01-01-201908000022015  2015           1           0 male
2  01-01-01-201908000032015  2015           1           0 male
3  01-01-01-201908000042015  2015           1           0 male
4  01-01-01-201908000052015  2015           1    -9998 unclear

  female_petitioner  female_adv_def  female_adv_pet  type_name  purpose_name  \
0          1 female           -9999               0     1978.0        6013.0
1          1 female               0               1     1978.0        5446.0
2            0 male           -9999               0     1978.0        6013.0
3            0 male           -9999               0     1978.0        6210.0
4            0 male               0               0     1978.0        6013.0

   disp_name
0         25
1         30
2         32
3         51
4         25

In [5]:
type_name = pd.read_csv('/kaggle/input/pre-cog/keys/type_name_key.csv')
print(type_name.head())

   year  type_name         type_name_s  count
0  2010        1.0            (m) t.s.     18
1  2010        2.0                (sc)      2
2  2010        3.0          ..mact 166     97
3  2010        4.0  04 complaint cases     19
4  2010        5.0    04 criminal case     21

In [6]:
type_name.drop(type_name[type_name['year'] != 2015].index, inplace = True)

In [7]:
print(type_name.head())

       year  type_name          type_name_s  count
32763  2015        NaN                  NaN     21
32764  2015        1.0             (m) t.s.    139
32765  2015        2.0               0.s.la      1
32766  2015        3.0  01 bail_application    700
32767  2015        4.0   01 criminal appeal     17

In [8]:
type_name.reset_index()

      index  year  type_name          type_name_s  count
0     32763  2015        NaN                  NaN     21
1     32764  2015        1.0             (m) t.s.    139
2     32765  2015        2.0               0.s.la      1
3     32766  2015        3.0  01 bail_application    700
4     32767  2015        4.0   01 criminal appeal     17
...     ...   ...        ...                  ...    ...
7473  40236  2015     7473.0    zcivil misc. case      1
7474  40237  2015     7474.0   zila panchayat act   1420
7475  40238  2015     7475.0  zilla panchayat act     10
7476  40239  2015     7476.0     zima 457 cr.p.c.      3
7477  40240  2015     7477.0    zimma application     60

[7478 rows x 5 columns]

In [9]:
type_name = type_name[(type_name['type_name_s'] == "divo cases") | (type_name['type_name_s'] == "divorce") | (type_name['type_name_s'] == "divorce case") | (type_name['type_name_s'] == "divorce on mutual consent") | (type_name['type_name_s'] == "divorce suit") | (type_name['type_name_s'] == "dmc") | (type_name['type_name_s'] == "dom viol") | (type_name['type_name_s'] == "domestic violence") | (type_name['type_name_s'] == "domestic violence ac") | (type_name['type_name_s'] == "domestic violence act 2005") | (type_name['type_name_s'] == "domestic violence act.") | (type_name['type_name_s'] == "domestic violence cases") | (type_name['type_name_s'] == "domestic voilenceact") | (type_name['type_name_s'] == "domestice violence act") | (type_name['type_name_s'] == "dop") | (type_name['type_name_s'] == "dowry prohibition act")]

In [10]:
print(type_name)

       year  type_name                 type_name_s  count
35232  2015     2469.0                  divo cases    121
35233  2015     2470.0                     divorce    279
35234  2015     2471.0                divorce case    307
35237  2015     2474.0   divorce on mutual consent   1821
35239  2015     2476.0                divorce suit      1
35242  2015     2479.0                         dmc  10784
35245  2015     2482.0                    dom viol     18
35252  2015     2489.0           domestic violence    750
35253  2015     2490.0        domestic violence ac     69
35255  2015     2492.0  domestic violence act 2005   3220
35258  2015     2495.0      domestic violence act.   1123
35260  2015     2497.0     domestic violence cases    344
35263  2015     2500.0        domestic voilenceact     95
35264  2015     2501.0      domestice violence act    618
35266  2015     2503.0                         dop    396
35267  2015     2504.0       dowry prohibition act     71

In [11]:
type_name = type_name.drop(['year'], axis=1)

In [12]:
mer_2018 = case_2018_b.merge(type_name, left_on="type_name", right_on="type_name", how="left")
print(mer_2018.head())

                ddl_case_id  year  state_code female_defendant  \
0  01-01-01-201908000012015  2015           1    -9998 unclear
1  01-01-01-201908000022015  2015           1           0 male
2  01-01-01-201908000032015  2015           1           0 male
3  01-01-01-201908000042015  2015           1           0 male
4  01-01-01-201908000052015  2015           1    -9998 unclear

  female_petitioner  female_adv_def  female_adv_pet  type_name  purpose_name  \
0          1 female           -9999               0     1978.0        6013.0
1          1 female               0               1     1978.0        5446.0
2            0 male           -9999               0     1978.0        6013.0
3            0 male           -9999               0     1978.0        6210.0
4            0 male               0               0     1978.0        6013.0

   disp_name type_name_s  count
0         25         NaN    NaN
1         30         NaN    NaN
2         32         NaN    NaN
3         51         NaN    NaN
4         25         NaN    NaN

In [13]:
mer_2018.dropna(subset=['type_name_s'], inplace=True)
print(mer_2018.head())

                     ddl_case_id  year  state_code female_defendant  \
619763  01-23-02-201300000312015  2015           1           0 male
619764  01-23-02-201300000372014  2015           1           0 male
619765  01-23-02-201300000722014  2015           1           0 male
619766  01-23-02-201300000722015  2015           1           0 male
619767  01-23-02-201300000732014  2015           1           0 male

       female_petitioner  female_adv_def  female_adv_pet  type_name  \
619763          1 female           -9999           -9999     2497.0
619764          1 female           -9999           -9999     2497.0
619765          1 female           -9999           -9999     2497.0
619766          1 female           -9999           -9999     2497.0
619767          1 female           -9999           -9999     2497.0

        purpose_name  disp_name              type_name_s  count
619763        3030.0         26  domestic violence cases  344.0
619764        5870.0         25  domestic violence cases  344.0
619765        3030.0         22  domestic violence cases  344.0
619766        3030.0         26  domestic violence cases  344.0
619767        3030.0         33  domestic violence cases  344.0

In [14]:
mer_2018_def = mer_2018

In [15]:
mer_2018.dropna(subset=['female_petitioner'], inplace=True)

In [16]:
mer_2018_final = mer_2018[(mer_2018['female_petitioner'] == "0 male") | (mer_2018['female_petitioner'] == "1 female")]
print(mer_2018_final.head())

                     ddl_case_id  year  state_code female_defendant  \
619763  01-23-02-201300000312015  2015           1           0 male
619764  01-23-02-201300000372014  2015           1           0 male
619765  01-23-02-201300000722014  2015           1           0 male
619766  01-23-02-201300000722015  2015           1           0 male
619767  01-23-02-201300000732014  2015           1           0 male

       female_petitioner  female_adv_def  female_adv_pet  type_name  \
619763          1 female           -9999           -9999     2497.0
619764          1 female           -9999           -9999     2497.0
619765          1 female           -9999           -9999     2497.0
619766          1 female           -9999           -9999     2497.0
619767          1 female           -9999           -9999     2497.0

        purpose_name  disp_name              type_name_s  count
619763        3030.0         26  domestic violence cases  344.0
619764        5870.0         25  domestic violence cases  344.0
619765        3030.0         22  domestic violence cases  344.0
619766        3030.0         26  domestic violence cases  344.0
619767        3030.0         33  domestic violence cases  344.0

In [17]:
fpet = mer_2018_final.groupby(['female_petitioner'])['ddl_case_id'].count().reset_index()
print(fpet)

  female_petitioner  ddl_case_id
0            0 male         7826
1          1 female        11224

In [18]:
fpet.rename(columns={fpet.columns[1]: '2015'},inplace=True)
print(fpet)

  female_petitioner   2015
0            0 male   7826
1          1 female  11224

In [19]:
fpet.to_csv('fpet_2015.csv')

In [20]:
mer_2018_def.dropna(subset=['female_defendant'], inplace=True)

In [21]:
mer_2018_def_final = mer_2018_def[(mer_2018_def['female_defendant'] == "0 male") | (mer_2018['female_defendant'] == "1 female")]
print(mer_2018_def_final.head())

                     ddl_case_id  year  state_code female_defendant  \
619763  01-23-02-201300000312015  2015           1           0 male
619764  01-23-02-201300000372014  2015           1           0 male
619765  01-23-02-201300000722014  2015           1           0 male
619766  01-23-02-201300000722015  2015           1           0 male
619767  01-23-02-201300000732014  2015           1           0 male

       female_petitioner  female_adv_def  female_adv_pet  type_name  \
619763          1 female           -9999           -9999     2497.0
619764          1 female           -9999           -9999     2497.0
619765          1 female           -9999           -9999     2497.0
619766          1 female           -9999           -9999     2497.0
619767          1 female           -9999           -9999     2497.0

        purpose_name  disp_name              type_name_s  count
619763        3030.0         26  domestic violence cases  344.0
619764        5870.0         25  domestic violence cases  344.0
619765        3030.0         22  domestic violence cases  344.0
619766        3030.0         26  domestic violence cases  344.0
619767        3030.0         33  domestic violence cases  344.0

In [22]:
fdef = mer_2018_def_final.groupby(['female_defendant'])['ddl_case_id'].count().reset_index()
print(fdef)

  female_defendant  ddl_case_id
0           0 male        11755
1         1 female         6600

In [23]:
fdef.rename(columns={fdef.columns[1]: '2015'},inplace=True)
print(fdef)

  female_defendant   2015
0           0 male  11755
1         1 female   6600

In [24]:
fdef.to_csv('fdef_2015.csv')